# Numpy Assignment 
# 50 methods using np

In [1]:
import numpy as np

In [3]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [4]:
np.ndim(a) # dimension of array

2

In [5]:
np.size(a) # total size of array

16

In [11]:
a
a.T # transpose

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [12]:
np.max(a) # maximum value of the array

15

In [13]:
np.sum(a) # total sum of array

120

In [14]:
np.mean(a) # average

7.5

In [15]:
np.square(a) # square of a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121],
       [144, 169, 196, 225]], dtype=int32)

In [16]:
np.min(a) # minimum value

0

In [17]:
np.sin(a) # sin of a

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021],
       [-0.53657292,  0.42016704,  0.99060736,  0.65028784]])

In [18]:
np.cos(a) # cos of a

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029,  0.75390225],
       [-0.14550003, -0.91113026, -0.83907153,  0.0044257 ],
       [ 0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [19]:
np.sqrt(a) # square root of a

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335]])

In [20]:
np.exp(a)   # exponential of a

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04],
       [1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06]])

In [21]:
q=np.empty((3,3)) # desired array 
q

array([[0.000e+000, 0.000e+000, 0.000e+000],
       [0.000e+000, 0.000e+000, 2.945e-321],
       [0.000e+000, 0.000e+000, 0.000e+000]])

In [22]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [23]:
np.linspace(0,5,10) # 10 numbers between 0 and 5

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [24]:
print(a)
print(q)
np.concatenate((a,q)) # concatenate the array store in a+q

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 2.945e-321]
 [0.000e+000 0.000e+000 0.000e+000]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3

In [25]:
print(q)
np.around(q,2) # round the array store variable q 

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 2.945e-321]
 [0.000e+000 0.000e+000 0.000e+000]]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
r=np.full((2,2),7, dtype="complex") # use array with iota=i
r

array([[7.+0.j, 7.+0.j],
       [7.+0.j, 7.+0.j]])

In [27]:
np.conjugate(r) #conjugate of variable r

array([[7.-0.j, 7.-0.j],
       [7.-0.j, 7.-0.j]])

In [28]:
i=np.array([1,2,3,4,5]) # increasing with the N
N=4
np.vander(i,N)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [ 64,  16,   4,   1],
       [125,  25,   5,   1]])

In [32]:
r=np.array([2,3,4,45,-5])
r

array([ 2,  3,  4, 45, -5])

In [33]:
np.abs(r) # absoulute the - value

array([ 2,  3,  4, 45,  5])

In [34]:
np.fabs(r) # float the integer value

array([ 2.,  3.,  4., 45.,  5.])

In [39]:
x=np.array([2.3,4.7,78.99,55.7])
x

array([ 2.3 ,  4.7 , 78.99, 55.7 ])

In [40]:
np.ceil(x) # round up 

array([ 3.,  5., 79., 56.])

In [41]:
np.floor(x) #round down

array([ 2.,  4., 78., 55.])

In [42]:
np.eye(5) # identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [52]:
t=np.array([2,2,2,5,6,7,88,33,56,1,1,1])
print(t)
x = np.unique(t)
x

[ 2  2  2  5  6  7 88 33 56  1  1  1]


array([ 1,  2,  5,  6,  7, 33, 56, 88])

In [48]:
arr1=([1,2,3,4,5,6,7])
arr2=([8,9,10,11,12,13,14])
na=np.union1d(arr1,arr2)
na

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [49]:
w=np.intersect1d(arr1,arr2) # no intersection so it gives empty array
w

array([], dtype=int32)

In [54]:
y=np.array([1,2,3,4,5,6])
print(y)
np.array_split(y,3) # array split 

[1 2 3 4 5 6]


[array([1, 2]), array([3, 4]), array([5, 6])]

In [59]:
u=np.array([[2,4,6],[4,68,9],[2,0,78]])
print(u)
t=np.hsplit(u,3) #horizontal split
t


[[ 2  4  6]
 [ 4 68  9]
 [ 2  0 78]]


[array([[2],
        [4],
        [2]]),
 array([[ 4],
        [68],
        [ 0]]),
 array([[ 6],
        [ 9],
        [78]])]

In [61]:
np.hstack(u) # hoorizontal stack

array([ 2,  4,  6,  4, 68,  9,  2,  0, 78])

In [62]:
np.vstack(u) # vertical stack

array([[ 2,  4,  6],
       [ 4, 68,  9],
       [ 2,  0, 78]])

In [70]:
o=np.array([1,2,3,4,5,6,]) #cond where
r=np.where(o >= 6)
r

(array([5], dtype=int64),)

In [71]:
np.searchsorted(o,5) # search the index number

4

In [72]:
a1=np.array([[0,23,4],[100,0,4],[33,56,2]]) # sorting
np.sort(a1)

array([[  0,   4,  23],
       [  0,   4, 100],
       [  2,  33,  56]])

In [79]:
a2=np.array([20,30,45,56])
filter_arr= a2 < 45 # filter array condition
a3=a2[filter_arr] # filter array stores in variable
print(filter_arr)
print(a3)


[ True  True False False]
[20 30]
